# Generated by Django 6.1.1 on 2026-09-16 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoAlimentar',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('unidade', models.CharField(help_text='Ex.: kg, L, saca', max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, help_text='Estoque atual', max_digits=10)),
            ],
            options={
                'verbose_name': 'Produto Alimentar',
                'verbose_name_plural': 'Produtos Alimentares',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoAlimentacao',
            fields=[
                ('id_tipo_alimentacao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Alimentação',
                'verbose_name_plural': 'Tipos de Alimentação',
            },
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id_dieta', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dietas', to='animais.setor')),
            ],
            options={
                'verbose_name': 'Dieta',
                'verbose_name_plural': 'Dietas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoSetor',
            fields=[
                ('id_consumo', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='animais.setor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='alimentacao.produtoalimentar')),
            ],
            options={
                'verbose_name': 'Consumo por Setor',
                'verbose_name_plural': 'Consumos por Setor',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Alimentacao',
            fields=[
                ('id_alimentacao', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentacoes', to='animais.animal')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alimentacoes', to='alimentacao.produtoalimentar')),
            ],
            options={
                'verbose_name': 'Alimentação',
                'verbose_name_plural': 'Alimentações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='DietaProduto',
            fields=[
                ('id_dieta_produto', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='alimentacao.dieta')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dietas', to='alimentacao.produtoalimentar')),
            ],
            options={
                'verbose_name': 'Produto da Dieta',
                'verbose_name_plural': 'Produtos da Dieta',
                'unique_together': {('dieta', 'produto')},
            },
        ),
    ]
