# Generated by Django 6.1 on 2026-09-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentacao',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tipoalimentacao',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
