# Generated by Django 6.1 on 2026-09-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(max_length=50, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.CharField(blank=True, max_length=50, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
