# Generated by Django 6.1.1 on 2026-09-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_alter_animal_especie_alter_animal_raca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='tipo',
            field=models.CharField(blank=True, choices=[('bovino_corte', 'Bovinocultura de corte'), ('bovino_leite', 'Bovinocultura de leite'), ('caprinocultura', 'Caprinocultura'), ('avicultura', 'Avicultura'), ('suinocultura', 'Suinocultura')], max_length=20, verbose_name='Tipo de produção'),
        ),
    ]
