# Generated by Django 6.1.1 on 2026-09-16 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProtocoloSanitario',
            fields=[
                ('id_protocolo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('periodicidade', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Protocolo Sanitário',
                'verbose_name_plural': 'Protocolos Sanitários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoMedicamento',
            fields=[
                ('id_tipo_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Medicamento',
                'verbose_name_plural': 'Tipos de Medicamento',
            },
        ),
        migrations.CreateModel(
            name='ViaAdministracao',
            fields=[
                ('id_via', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Via de Administração',
                'verbose_name_plural': 'Vias de Administração',
            },
        ),
        migrations.CreateModel(
            name='HistoricoSanitario',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('tipo_evento', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_sanitario', to='animais.animal')),
            ],
            options={
                'verbose_name': 'Histórico Sanitário',
                'verbose_name_plural': 'Históricos Sanitários',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(max_length=150)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id_ocorrencia', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('sintomas', models.TextField()),
                ('observacao', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='animais.animal')),
                ('diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='sanitario.diagnostico')),
            ],
            options={
                'verbose_name': 'Ocorrência Sanitária',
                'verbose_name_plural': 'Ocorrências Sanitárias',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='PrescricaoVeterinaria',
            fields=[
                ('id_prescricao', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('dosagem', models.CharField(max_length=100)),
                ('frequencia', models.CharField(max_length=100)),
                ('duracao', models.CharField(blank=True, max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes', to='animais.animal')),
            ],
            options={
                'verbose_name': 'Prescrição Veterinária',
                'verbose_name_plural': 'Prescrições Veterinárias',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RegistroSanitario',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_sanitarios', to='animais.animal')),
            ],
            options={
                'verbose_name': 'Registro Sanitário',
                'verbose_name_plural': 'Registros Sanitários',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioSanitario',
            fields=[
                ('id_relatorio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório Sanitário',
                'verbose_name_plural': 'Relatórios Sanitários',
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('principio_ativo', models.CharField(blank=True, max_length=150)),
                ('apresentacao', models.CharField(blank=True, max_length=100)),
                ('tipo_medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicamentos', to='sanitario.tipomedicamento')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id_tratamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('protocolo', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=20)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos', to='animais.animal')),
                ('diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamentos', to='sanitario.diagnostico')),
            ],
            options={
                'verbose_name': 'Tratamento',
                'verbose_name_plural': 'Tratamentos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TratamentoMedicamento',
            fields=[
                ('id_tratamento_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('dose', models.CharField(max_length=100)),
                ('frequencia', models.CharField(max_length=100)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamentos_utilizados', to='sanitario.medicamento')),
                ('tratamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_utilizados', to='sanitario.tratamento')),
            ],
            options={
                'verbose_name': 'Medicamento do Tratamento',
                'verbose_name_plural': 'Medicamentos do Tratamento',
            },
        ),
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('id_vacinacao', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('dose', models.CharField(max_length=100)),
                ('proxima_dose', models.DateField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinacoes', to='animais.animal')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacinacoes', to='sanitario.medicamento')),
            ],
            options={
                'verbose_name': 'Vacinação',
                'verbose_name_plural': 'Vacinações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Vermifugacao',
            fields=[
                ('id_vermifugacao', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('dose', models.CharField(max_length=100)),
                ('proxima_aplicacao', models.DateField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vermifugacoes', to='animais.animal')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vermifugacoes', to='sanitario.medicamento')),
            ],
            options={
                'verbose_name': 'Vermifugação',
                'verbose_name_plural': 'Vermifugações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AplicacaoMedicamento',
            fields=[
                ('id_aplicacao', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('dose', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='animais.animal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicacoes', to=settings.AUTH_USER_MODEL)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes', to='sanitario.medicamento')),
                ('via_aplicacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicacoes', to='sanitario.viaadministracao')),
            ],
            options={
                'verbose_name': 'Aplicação de Medicamento',
                'verbose_name_plural': 'Aplicações de Medicamentos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ProtocoloSetor',
            fields=[
                ('id_protocolo_setor', models.AutoField(primary_key=True, serialize=False)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='sanitario.protocolosanitario')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocolos', to='animais.setor')),
            ],
            options={
                'verbose_name': 'Protocolo por Setor',
                'verbose_name_plural': 'Protocolos por Setor',
                'unique_together': {('protocolo', 'setor')},
            },
        ),
    ]