# Generated by Django 6.1 on 2026-09-22 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacaomedicamento',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='aplicacaomedicamento',
            name='via_aplicacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicacoes', to='sanitario.viaadministracao', verbose_name='Via de aplicação'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='historicosanitario',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='historicosanitario',
            name='tipo_evento',
            field=models.CharField(max_length=100, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(max_length=150, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='apresentacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apresentação'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='principio_ativo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Princípio ativo'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='diagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='sanitario.diagnostico', verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='prescricaoveterinaria',
            name='duracao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='prescricaoveterinaria',
            name='frequencia',
            field=models.CharField(max_length=100, verbose_name='Frequência'),
        ),
        migrations.AlterField(
            model_name='prescricaoveterinaria',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='protocolosanitario',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='registrosanitario',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='relatoriosanitario',
            name='data_geracao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de geração'),
        ),
        migrations.AlterField(
            model_name='relatoriosanitario',
            name='periodo_fim',
            field=models.DateField(verbose_name='Fim do período'),
        ),
        migrations.AlterField(
            model_name='relatoriosanitario',
            name='periodo_inicio',
            field=models.DateField(verbose_name='Início do período'),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='diagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamentos', to='sanitario.diagnostico', verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='tratamentomedicamento',
            name='frequencia',
            field=models.CharField(max_length=100, verbose_name='Frequência'),
        ),
        migrations.AlterField(
            model_name='vacinacao',
            name='proxima_dose',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima dose'),
        ),
        migrations.AlterField(
            model_name='vermifugacao',
            name='proxima_aplicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima aplicação'),
        ),
        migrations.AlterField(
            model_name='viaadministracao',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
