# Generated by Django 6.1 on 2026-09-28 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitario', '0002_alter_aplicacaomedicamento_observacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='diagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='sanitario.diagnostico', verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='diagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamentos', to='sanitario.diagnostico', verbose_name='Diagnóstico'),
        ),
    ]
